# Configurazione per produzione
spring:
  # Database di produzione
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notabene_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  # JPA per produzione
  jpa:
    hibernate:
      ddl-auto: validate  # Non modificare schema in produzione
    show-sql: false       # Non mostrare SQL in produzione
    
# Server per produzione
server:
  port: ${PORT:8080}
  
# Logging per produzione
logging:
  level:
    root: INFO
    com.notabene: INFO
    org.springframework: WARN
    org.hibernate: WARN
  
# Actuator sicuro per produzione
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
