# Configurazione per profilo di sviluppo
spring:
  # Database di sviluppo locale
  datasource:
    url: jdbc:postgresql://localhost:5432/notabene_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  
  # JPA per sviluppo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
# Logging più dettagliato per sviluppo
logging:
  level:
    com.notabene: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
